[package]
name = "regchest_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.17.1"
futures = "0.3.28"

[dev-dependencies]
tokio =  { version = "1.32.0", features = ["full"] }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

